-- 코드를 작성해주세요

# 더이상 업그레이드 못하는 아이템의 ID, 이름, 희귀도
# 업그레이드 불가 = 아무도 이 아이템 ID를 PARENT_ITEM_ID로 갖지 않아야 함
SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID
FROM ITEM_TREE
WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC