# 상품코드별 매출액 합계
SELECT PRODUCT.PRODUCT_CODE, (PRODUCT.PRICE*TS.TOTAL_SALES) AS SALES
FROM PRODUCT LEFT JOIN
    (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS TOTAL_SALES
    FROM OFFLINE_SALE
    GROUP BY PRODUCT_ID) AS TS
    ON PRODUCT.PRODUCT_ID=TS.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC