-- 보호소 들어올 땐 중성화x > 보호소 나갈 땐 중성화된 동물의 ID/생물 종/이름을 ID 순으로 조회
SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.ANIMAL_TYPE, ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS INNER JOIN ANIMAL_INS ON ANIMAL_OUTS.ANIMAL_ID=ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE 'Intact%' AND ANIMAL_INS.SEX_UPON_INTAKE LIKE 'Intact%'
ORDER BY ANIMAL_OUTS.ANIMAL_ID