-- 생산일자가 2022년 5월인 식품들의 식품 ID, 식품 이름, 총매출
SELECT FOOD_ORDER.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME, SUM(FOOD_ORDER.AMOUNT*FOOD_PRODUCT.PRICE) AS TOTAL_AMOUNT
FROM FOOD_ORDER LEFT JOIN FOOD_PRODUCT ON FOOD_ORDER.PRODUCT_ID=FOOD_PRODUCT.PRODUCT_ID
WHERE YEAR(FOOD_ORDER.PRODUCE_DATE)=2022 AND MONTH(FOOD_ORDER.PRODUCE_DATE)=5 AND FOOD_PRODUCT.PRODUCT_NAME IS NOT NULL
GROUP BY FOOD_ORDER.PRODUCT_ID
ORDER BY TOTAL_AMOUNT DESC, PRODUCT_ID ASC