SELECT FIRST_HALF.FLAVOR
FROM FIRST_HALF JOIN 
(SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR) AS JULY ON FIRST_HALF.FLAVOR=JULY.FLAVOR
ORDER BY (FIRST_HALF.TOTAL_ORDER+JULY.TOTAL_ORDER) DESC
LIMIT 3