-- 코드를 작성해주세요
SELECT DEVELOPERS.ID, DEVELOPERS.EMAIL, DEVELOPERS.FIRST_NAME, DEVELOPERS.LAST_NAME
FROM
    DEVELOPERS,
    (SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY='Front End') AS SC
WHERE DEVELOPERS.SKILL_CODE & SC.CODE != 0
ORDER BY DEVELOPERS.ID ASC