# # -- 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회하기

SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM
    (SELECT *
    FROM REST_REVIEW
    WHERE MEMBER_ID=(SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)) AS A LEFT JOIN
    MEMBER_PROFILE AS B
    ON A.MEMBER_ID=B.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC