SELECT M_S.YEAR, (M_S.MAX_SIZE - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV, ECOLI_DATA.ID
FROM ECOLI_DATA JOIN
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)) AS M_S
    ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE)=M_S.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC