-- 부서별 평균 연봉
SELECT D.DEPT_ID, D.DEPT_NAME_EN, E.AVG_SAL
FROM HR_DEPARTMENT AS D INNER JOIN
(SELECT DEPT_ID, ROUND(AVG(SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES
GROUP BY DEPT_ID) AS E ON D.DEPT_ID=E.DEPT_ID
ORDER BY E.AVG_SAL DESC