-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', USED_GOODS_FILE.FILE_ID, USED_GOODS_FILE.FILE_NAME, USED_GOODS_FILE.FILE_EXT) AS FILE_PATH
FROM (SELECT BOARD_ID, VIEWS
FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS A LEFT JOIN USED_GOODS_FILE ON A.BOARD_ID=USED_GOODS_FILE.BOARD_ID
ORDER BY FILE_ID DESC