-- 코드를 입력하세요

SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('식용유','과자','김치','국') AND PRICE IN
    (SELECT MAX(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY)
ORDER BY PRICE DESC